-- =============================================================================
-- Entity Aliases Table
-- =============================================================================
-- Caches LLM-generated aliases for entities to avoid repeated API calls.
-- Aliases are generated by GPT-4o-mini and include nicknames, shortened forms,
-- and alternative names that may appear in news headlines.
--
-- Created: 2026-01-28
-- =============================================================================

-- Create entity_aliases table
CREATE TABLE IF NOT EXISTS entity_aliases (
    id BIGSERIAL PRIMARY KEY,
    entity_id TEXT NOT NULL UNIQUE,          -- Normalized entity ID (e.g., "pam_bondi")
    canonical_name TEXT NOT NULL,            -- Full entity name (e.g., "Pam Bondi")
    aliases JSONB NOT NULL DEFAULT '[]',     -- Array of aliases (e.g., ["bondi", "pam", "ag bondi"])
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fast lookups by entity_id
CREATE INDEX IF NOT EXISTS idx_entity_aliases_entity_id ON entity_aliases(entity_id);

-- Index for searching within aliases JSONB array
CREATE INDEX IF NOT EXISTS idx_entity_aliases_aliases ON entity_aliases USING GIN (aliases);

-- Add comment explaining the table
COMMENT ON TABLE entity_aliases IS 'Caches LLM-generated aliases for entity matching. Populated by EntityMarketIndex._generate_llm_aliases()';
COMMENT ON COLUMN entity_aliases.entity_id IS 'Normalized entity ID (lowercase, underscored)';
COMMENT ON COLUMN entity_aliases.canonical_name IS 'Human-readable entity name from Kalshi yes_sub_title';
COMMENT ON COLUMN entity_aliases.aliases IS 'JSON array of LLM-generated aliases for matching';

-- Enable RLS (Row Level Security) for Supabase
ALTER TABLE entity_aliases ENABLE ROW LEVEL SECURITY;

-- Allow all operations for authenticated users (service role)
CREATE POLICY "Allow all for service role" ON entity_aliases
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Grant permissions
GRANT ALL ON entity_aliases TO authenticated;
GRANT ALL ON entity_aliases TO service_role;
GRANT USAGE, SELECT ON SEQUENCE entity_aliases_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE entity_aliases_id_seq TO service_role;
